#!/bin/bash
./scripts/export-build opbeat-js ../opbeat-js-release/ ./dist/opbeat-js/*

cd ../opbeat-js-release/

folder=${PWD##*/}
echo $folder
if [ $folder=="opbeat-js-release" ]
  then
    npm publish
fi