#!/bin/bash
./scripts/export-build opbeat-angular ../opbeat-angular-release/ ./dist/opbeat-angular/*

cd ../opbeat-angular-release/

folder=${PWD##*/}
echo $folder
if [ $folder=="opbeat-angular-release" ]
  then
    npm publish
fi